"""Align models

Revision ID: 27dac9378703
Revises: 
Create Date: 2026-07-30 20:28:20.190781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27dac9378703'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_display_order', 'platform_module_fields', ['display_order'], unique=False)
    op.create_index('idx_field_name', 'platform_module_fields', ['field_name'], unique=False)
    op.create_foreign_key(
    "fk_platform_module_fields_lookup_module",
    "platform_module_fields",
    "platform_modules",
    ["lookup_module_id"],
    ["id"],
)
    op.alter_column('platform_modules', 'menu_order',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_create',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_edit',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_delete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_view',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_export',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_import',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_print',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_workflow',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_attachment',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_comments',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_audit',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_versioning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_soft_delete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE', collation='utf8mb4_general_ci'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform_modules', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE', collation='utf8mb4_general_ci'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('platform_modules', 'enable_soft_delete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_versioning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_audit',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_comments',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_attachment',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_workflow',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_print',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_import',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_export',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('platform_modules', 'enable_view',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_delete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_edit',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'enable_create',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('platform_modules', 'menu_order',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(
    "fk_platform_module_fields_lookup_module",
    "platform_module_fields",
    type_="foreignkey",
)
    op.drop_index('idx_field_name', table_name='platform_module_fields')
    op.drop_index('idx_display_order', table_name='platform_module_fields')
    # ### end Alembic commands ###
