"""update roles table

Revision ID: 86d79dfa0e47
Revises: 88155222d468
Create Date: 2026-07-31 17:13:16.170598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86d79dfa0e47'
down_revision: Union[str, Sequence[str], None] = '88155222d468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('roles', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('roles', 'created_by',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('roles', 'updated_by',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    #op.drop_index(op.f('ix_roles_id'), table_name='roles')
    #op.drop_index(op.f('ix_roles_name'), table_name='roles')
    #op.create_index('idx_role_status', 'roles', ['status'], unique=False)
    op.create_unique_constraint(
        "uq_roles_role_code",
        "roles",
        ["role_code"],
    )
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False))
    op.drop_constraint(
        "uq_roles_role_code",
        "roles",
        type_="unique",
    )
    op.drop_index('idx_role_status', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('roles', 'updated_by',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('roles', 'created_by',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.alter_column('roles', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('roles', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
